services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_auth_db
    environment:
      POSTGRES_USER: ${DB_USER:-dev_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_DB: ${DB_NAME:-template_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-dev_user} -d ${DB_NAME:-template_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_auth_cache
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin_ui:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_CONFIG_COOKIE_SAMESITE: 'None'
      PGADMIN_CONFIG_COOKIE_SECURE: 'True'
    ports:
      - "5050:80"
    depends_on:
      - db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_api
    ports:
      - "8080:8080"
    profiles:
      - prod
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME:-template_db}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-dev_user}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-1234}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
volumes:
  postgres_data: